[parity]
chain = "demo-spec.json"
base_path = "node0"
[network]
port = 30300
warp = true
allow_ips = "all"
[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
interface = "0.0.0.0"
hosts = ["all"]
[ui]
port = 8180
interface = "0.0.0.0"
[dapps]
port = 8080
interface = "0.0.0.0"
hosts = ["all"]
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x14ebbeaaa21d256757c09c8ce3d09f74aa04e688"
reseal_on_txs = "none"
